apiVersion: apps/v1
kind: Deployment
metadata:
  name: govbridge-backend
  namespace: govbridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: govbridge-backend
  template:
    metadata:
      labels:
        app: govbridge-backend
    spec:
      containers:
        - name: backend
          image: 290373175461.dkr.ecr.us-east-2.amazonaws.com/govbridge-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "govbridge-db.ch2i4wo48ol1.us-east-2.rds.amazonaws.com"
            - name: DB_NAME
              value: "govbridge"
            - name: DB_USERNAME
              value: "govbridge_admin"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: govbridge-secrets
                  key: db-password
            - name: KAFKA_BROKERS
              value: "localhost:9092"
            - name: CHAIN_RPC_URL
              value: "https://base-sepolia.infura.io/v3/935a9f7050ae4a26aeaa9077407991c3"
            - name: DEPLOYER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: govbridge-secrets
                  key: deployer-private-key
            - name: DOC_VERIFY_ADDRESS
              value: "0x9Cefaa1c05d4af7cB499a93B9d958B91a0eFEa88"
            - name: PAYMENT_RECEIPT_ADDRESS
              value: "0x80051165044a88e6eBa0CEba574e792BF6de0DAB"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: govbridge-backend
  namespace: govbridge
spec:
  selector:
    app: govbridge-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
